version: '3'

services: 
    db:
        build: ./db
        tty: true
        ports: 
            - "3306:3306"
        container_name: db
        environment: 
            MYSQL_ROOT_PASSWORD: CustomRoom1!
            MYSQL_DATABASE: CustomRoom

    golang:
        build: ./go
        tty: true
        ports:
            - "8080:8080"
        container_name: golang
        links:
            - db
            - react
        volumes:
            - ./go:/go/src
            
    react:
        build: ./react
        tty: true
        ports: 
            - "3000:3000"
        container_name: react
        volumes: 
            - ./react:/usr/src
